version: "3"

services: 
  api:
    build: .
    env_file: 
      - ./.env
    restart: unless-stopped
    ports:
      - "${PORT:${PORT}"
    depends_on: 
      - db
      - redis_db

  db:
    image: mariadb:10.6.4
    volumes: 
      - ./resources/db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dockerdata:/var/lib/mysql
    expose: 
      - 3306
    restart: unless-stopped

  redis_db:
    image: redis:latest
    expose: 
      - 6379
    restart: unless-stopped